// STORY MODE — scénarios décrits par des données (moteur : buildScenario dans scenarios.js).
// Chaque scénario : pays, situation de départ, objectif principal, objectifs secondaires et secrets,
// conditions d'échec, événements datés, difficulté conseillée. Mises en scène de jeu, pas des prévisions.
const S = (o) => o;

export const STORY = [
  // ======================= ÉCONOMIE =======================
  S({ id: 'st-tigre', cats: ['eco'], country: 'VN', years: 12, difficulty: 'normal', icon: 'trending-up', tag: 'Économie', title: 'Le tigre du Mékong',
    desc: "Une main-d'œuvre jeune, des usines qui s'installent : faites du pays une puissance exportatrice sans perdre le contrôle de la dette.",
    start: { gdp: -5 },
    objectives: [{ type: 'gdp', value: 2, main: true }, { type: 'trade', value: 4 }, { type: 'debt', value: 60, optional: true }, { type: 'rank', value: 25, secret: true }],
    fails: [{ type: 'stability', value: 30 }],
    events: [{ at: 3, title: 'Délocalisations massives', text: 'Plusieurs groupes étrangers ouvrent des usines géantes.', fx: { gdp: 0.04, trade: 6 }, tone: 'good' },
      { at: 7, title: 'Choc des matières premières', text: 'La hausse des prix mondiaux pèse sur les exportateurs.', fx: { gdp: -0.05, stability: -5 }, tone: 'bad' }] }),
  S({ id: 'st-rente', cats: ['eco'], country: 'NG', years: 15, difficulty: 'hard', icon: 'droplets', tag: 'Économie', title: 'Après le pétrole',
    desc: 'La rente pétrolière s’effondre. Diversifiez l’économie avant que le budget ne s’écroule.',
    start: { gdp: -12, debt: 55, stability: -8 },
    objectives: [{ type: 'gdp', value: 1.4, main: true }, { type: 'projects', value: 5 }, { type: 'stability', value: 60 }, { type: 'infra', value: 12, secret: true }],
    fails: [{ type: 'debt', value: 160 }, { type: 'stability', value: 20 }],
    events: [{ at: 2, title: 'Baril au plus bas', text: 'Les cours du brut chutent encore.', fx: { gdp: -0.06, money: -0.01 }, tone: 'bad' }] }),
  S({ id: 'st-austerite', cats: ['eco', 'crises'], country: 'IT', years: 10, difficulty: 'hard', icon: 'scale', tag: 'Économie', title: 'Le pacte de stabilité',
    desc: 'Vos partenaires exigent une dette sous contrôle. Réduisez le déficit sans casser la croissance ni la paix sociale.',
    start: { debt: 150, money: 0.5, stability: -6 },
    objectives: [{ type: 'debt', value: 120, main: true }, { type: 'stability', value: 55 }, { type: 'gdp', value: 1.1, optional: true }],
    fails: [{ type: 'stability', value: 25 }],
    events: [{ at: 4, title: 'Grève générale', text: 'Les syndicats paralysent le pays contre les coupes budgétaires.', fx: { stability: -9, gdp: -0.02 }, tone: 'bad' }] }),
  S({ id: 'st-tresor', cats: ['eco'], country: 'NO', years: 8, difficulty: 'discovery', icon: 'banknote', tag: 'Économie', title: 'Le fonds souverain',
    desc: 'Les revenus abondent. Constituez des réserves solides et préparez l’après-rente.',
    objectives: [{ type: 'money', value: 12, main: true }, { type: 'tech', value: 5 }, { type: 'projects', value: 4, optional: true }],
    fails: [{ type: 'debt', value: 80 }] }),
  S({ id: 'st-emergent', cats: ['eco', 'dev'], country: 'BD', years: 15, difficulty: 'normal', icon: 'factory', tag: 'Économie', title: 'De l’atelier au marché',
    desc: 'Le textile fait vivre le pays. Montez en gamme et faites entrer l’économie dans le premier cercle régional.',
    objectives: [{ type: 'gdp', value: 2.2, main: true }, { type: 'techLevel', value: 55 }, { type: 'trade', value: 3 }, { type: 'pop', value: 12, secret: true }],
    fails: [{ type: 'stability', value: 25 }] }),

  // ======================= DIPLOMATIE =======================
  S({ id: 'st-mediateur', cats: ['diplo'], country: 'CH', years: 8, difficulty: 'normal', icon: 'handshake', tag: 'Diplomatie', title: 'La table des négociations',
    desc: 'Deux voisins se déchirent à vos portes. Restez neutre, gardez la confiance de tous et faites prospérer le commerce.',
    start: { aiWars: [['DE', 'FR']] },
    objectives: [{ type: 'peace', main: true }, { type: 'trade', value: 5 }, { type: 'relation', value: 50, target: 'FR' }, { type: 'relation', value: 50, target: 'DE', secret: true }],
    fails: [{ type: 'war' }] }),
  S({ id: 'st-reconciliation', cats: ['diplo'], country: 'KR', years: 10, difficulty: 'hard', icon: 'handshake', tag: 'Diplomatie', title: 'La main tendue',
    desc: 'Après des décennies d’hostilité, une fenêtre s’ouvre avec le Nord. Construisez la paix sans baisser la garde.',
    start: { rival: 'KP', rivalRel: -80 },
    objectives: [{ type: 'relation', value: 0, target: 'KP', main: true }, { type: 'peace' }, { type: 'alliances', value: 2, optional: true }],
    fails: [{ type: 'capital' }],
    events: [{ at: 2, title: 'Incident frontalier', text: 'Des tirs sur la ligne de démarcation ravivent la méfiance.', rel: { KP: -20 }, tone: 'bad' },
      { at: 6, title: 'Rencontre historique', text: 'Les deux dirigeants se serrent la main.', rel: { KP: 15 }, tone: 'good' }] }),
  S({ id: 'st-coalition', cats: ['diplo', 'geo'], country: 'PL', years: 8, difficulty: 'normal', icon: 'shield', tag: 'Diplomatie', title: 'Le rempart de l’Est',
    desc: 'Rassemblez vos voisins dans une coalition défensive avant qu’une puissance voisine ne passe à l’acte.',
    start: { personalities: { RU: 'expansionist' }, hostile: ['RU'] },
    objectives: [{ type: 'alliances', value: 4, main: true }, { type: 'army', value: 1.3 }, { type: 'territory', value: 0, optional: true }],
    fails: [{ type: 'capital' }] }),
  S({ id: 'st-pivot', cats: ['diplo'], country: 'TR', years: 10, difficulty: 'expert', icon: 'compass', tag: 'Diplomatie', title: 'Entre deux mondes',
    desc: 'Courtisé par tous, allié de personne : tirez le meilleur de chaque camp sans vous laisser enfermer.',
    objectives: [{ type: 'trade', value: 6, main: true }, { type: 'relation', value: 40, target: 'RU' }, { type: 'relation', value: 40, target: 'US' }, { type: 'rank', value: 12, secret: true }],
    fails: [{ type: 'stability', value: 25 }] }),
  S({ id: 'st-unite-africaine', cats: ['diplo', 'dev'], country: 'KE', years: 12, difficulty: 'normal', icon: 'network', tag: 'Diplomatie', title: 'Le marché commun',
    desc: 'Fédérez l’Afrique de l’Est autour d’un grand marché régional.',
    objectives: [{ type: 'trade', value: 5, main: true }, { type: 'relation', value: 60, target: 'TZ' }, { type: 'relation', value: 60, target: 'ET' }, { type: 'gdp', value: 1.5, secret: true }],
    fails: [{ type: 'war' }] }),

  // ======================= DÉVELOPPEMENT =======================
  S({ id: 'st-routes', cats: ['dev', 'villes'], country: 'ET', years: 15, difficulty: 'normal', icon: 'route', tag: 'Développement', title: 'Les routes du plateau',
    desc: 'Désenclavez un pays immense : routes, rail et électricité doivent atteindre chaque région.',
    start: { infra: -20 },
    objectives: [{ type: 'infra', value: 20, main: true }, { type: 'projects', value: 6 }, { type: 'pop', value: 15, optional: true }, { type: 'gdp', value: 1.8, secret: true }],
    fails: [{ type: 'stability', value: 22 }] }),
  S({ id: 'st-ecole', cats: ['dev'], country: 'IN', years: 12, difficulty: 'hard', icon: 'graduation-cap', tag: 'Développement', title: 'La décennie du savoir',
    desc: 'Misez sur l’éducation et la recherche pour transformer la puissance démographique en puissance économique.',
    objectives: [{ type: 'tech', value: 10, main: true }, { type: 'projects', value: 8 }, { type: 'rank', value: 3, secret: true }],
    fails: [{ type: 'debt', value: 140 }] }),
  S({ id: 'st-verte', cats: ['dev'], country: 'CR', years: 10, difficulty: 'discovery', icon: 'sprout', tag: 'Développement', title: 'Le modèle vert',
    desc: 'Un petit pays en paix veut prouver qu’on peut prospérer sans armée ni pollution.',
    objectives: [{ type: 'peace', main: true }, { type: 'stability', value: 75 }, { type: 'gdp', value: 1.3 }, { type: 'trade', value: 3, secret: true }],
    fails: [{ type: 'war' }] }),
  S({ id: 'st-reconstruire', cats: ['dev', 'survie'], country: 'SY', years: 12, difficulty: 'expert', icon: 'shovel', tag: 'Développement', title: 'Rebâtir',
    desc: 'Des années de guerre ont tout détruit. Rétablissez l’État, les infrastructures et la confiance.',
    start: { infra: -45, stability: -20, gdp: -25, debt: 90 },
    objectives: [{ type: 'infra', value: 25, main: true }, { type: 'stability', value: 55 }, { type: 'gdp', value: 1.5 }, { type: 'debt', value: 70, secret: true }],
    fails: [{ type: 'stability', value: 15 }] }),

  // ======================= TECHNOLOGIE =======================
  S({ id: 'st-puces', cats: ['tech'], country: 'IL', years: 10, difficulty: 'hard', icon: 'cpu', tag: 'Technologie', title: 'La nation start-up',
    desc: 'Vos laboratoires et vos jeunes entreprises font tourner le monde. Restez en tête de la course technologique malgré les menaces.',
    start: { rival: 'IR', rivalRel: -60 },
    objectives: [{ type: 'techLevel', value: 95, main: true }, { type: 'trade', value: 4 }, { type: 'alliances', value: 1, optional: true }, { type: 'money', value: 10, secret: true }],
    fails: [{ type: 'capital' }] }),
  S({ id: 'st-spatial', cats: ['tech'], country: 'BR', years: 15, difficulty: 'normal', icon: 'atom', tag: 'Technologie', title: 'Objectif orbite',
    desc: 'Le pays veut sa place parmi les puissances spatiales et technologiques.',
    objectives: [{ type: 'techLevel', value: 80, main: true }, { type: 'projects', value: 8 }, { type: 'gdp', value: 1.4, optional: true }] }),
  S({ id: 'st-rattrapage', cats: ['tech', 'dev'], country: 'ID', years: 15, difficulty: 'normal', icon: 'zap', tag: 'Technologie', title: 'Le grand rattrapage',
    desc: 'Comblez l’écart technologique avec les pays industrialisés en une génération.',
    objectives: [{ type: 'tech', value: 15, main: true }, { type: 'infra', value: 15 }, { type: 'rank', value: 8, secret: true }],
    fails: [{ type: 'stability', value: 25 }] }),
  S({ id: 'st-cyber', cats: ['tech', 'crises'], country: 'EE', years: 6, difficulty: 'hard', icon: 'monitor', tag: 'Technologie', title: 'L’État numérique',
    desc: 'Votre pays est le plus connecté du monde… et la cible d’attaques permanentes.',
    start: { hostile: ['RU'] },
    objectives: [{ type: 'techLevel', value: 92, main: true }, { type: 'alliances', value: 3 }, { type: 'stability', value: 70, optional: true }],
    fails: [{ type: 'capital' }],
    events: [{ at: 1.5, title: 'Cyberattaque géante', text: 'Les administrations sont paralysées pendant plusieurs jours.', fx: { stability: -8, gdp: -0.03 }, tone: 'bad' }] }),

  // ======================= GÉOPOLITIQUE =======================
  S({ id: 'st-detroit', cats: ['geo'], country: 'EG', years: 10, difficulty: 'normal', icon: 'ship', tag: 'Géopolitique', title: 'Le canal',
    desc: 'Le commerce mondial passe par chez vous. Gardez la route ouverte et profitez-en.',
    objectives: [{ type: 'trade', value: 6, main: true }, { type: 'stability', value: 60 }, { type: 'army', value: 1.2, optional: true }],
    fails: [{ type: 'war' }] }),
  S({ id: 'st-arctique', cats: ['geo'], country: 'CA', years: 12, difficulty: 'hard', icon: 'snowflake', tag: 'Géopolitique', title: 'La route du Nord',
    desc: 'La fonte des glaces ouvre de nouvelles routes et attise les convoitises sur le Grand Nord.',
    objectives: [{ type: 'territory', value: 0, main: true }, { type: 'alliances', value: 3 }, { type: 'infra', value: 10 }, { type: 'trade', value: 5, secret: true }] }),
  S({ id: 'st-heritier', cats: ['geo'], country: 'SA', years: 10, difficulty: 'expert', icon: 'crown', tag: 'Géopolitique', title: 'Le jeune prince',
    desc: 'Transformez le royaume, diversifiez l’économie et imposez-vous comme puissance régionale face à votre grand rival.',
    start: { rival: 'IR', rivalRel: -60 },
    objectives: [{ type: 'gdp', value: 1.3, main: true }, { type: 'alliances', value: 3 }, { type: 'techLevel', value: 75 }, { type: 'relation', value: 0, target: 'IR', secret: true }],
    fails: [{ type: 'stability', value: 25 }] }),
  S({ id: 'st-sahel', cats: ['geo', 'survie'], country: 'ML', years: 8, difficulty: 'expert', icon: 'shield', tag: 'Géopolitique', title: 'Les sables du Sahel',
    desc: 'Un État fragile, des frontières poreuses, des voisins instables. Tenez le pays.',
    start: { stability: -18, gdp: -8 },
    objectives: [{ type: 'territory', value: 5, main: true }, { type: 'stability', value: 50 }, { type: 'alliances', value: 2, optional: true }],
    fails: [{ type: 'capital' }, { type: 'stability', value: 10 }] }),

  // ======================= SURVIE =======================
  S({ id: 'st-assiege', cats: ['survie'], country: 'AM', years: 6, difficulty: 'hard', icon: 'shield', tag: 'Survie', title: 'Le pays assiégé',
    desc: 'Un voisin hostile attaque. Résistez, trouvez des soutiens et sauvez ce qui peut l’être.',
    start: { rival: 'AZ', rivalRel: -90, war: true },
    objectives: [{ type: 'survive', main: true }, { type: 'territory', value: 20 }, { type: 'alliances', value: 1, optional: true }],
    fails: [{ type: 'capital' }] }),
  S({ id: 'st-ile', cats: ['survie'], country: 'PH', years: 8, difficulty: 'grand', icon: 'anchor', tag: 'Survie', title: 'L’archipel',
    desc: 'Un voisin géant revendique vos îles et la menace d’un débarquement se précise. Préparez la défense et évitez l’isolement.',
    start: { rival: 'CN', rivalRel: -85, personalities: { CN: 'expansionist' } },
    objectives: [{ type: 'survive', main: true }, { type: 'army', value: 1.5 }, { type: 'alliances', value: 2 }, { type: 'peace', secret: true }],
    fails: [{ type: 'capital' }],
    events: [{ at: 3, title: 'Manœuvres géantes', text: 'Des exercices navals encerclent l’île.', rel: { CN: -15 }, fx: { stability: -4 }, tone: 'bad' }] }),
  S({ id: 'st-effondrement', cats: ['survie', 'crises'], country: 'VE', years: 8, difficulty: 'expert', icon: 'trending-down', tag: 'Survie', title: 'L’effondrement',
    desc: 'Hyperinflation, pénuries, exode : le pays est au bord du gouffre.',
    start: { gdp: -35, stability: -25, debt: 160, money: 0 },
    objectives: [{ type: 'stability', value: 45, main: true }, { type: 'gdp', value: 1.3 }, { type: 'debt', value: 110, optional: true }],
    fails: [{ type: 'stability', value: 8 }] }),
  S({ id: 'st-blocus', cats: ['survie', 'geo'], country: 'CU', years: 8, difficulty: 'hard', icon: 'anchor', tag: 'Survie', title: 'Le blocus',
    desc: 'Isolé, sous embargo, le pays doit trouver de nouveaux partenaires pour survivre.',
    start: { relAll: -25, gdp: -10 },
    objectives: [{ type: 'trade', value: 3, main: true }, { type: 'stability', value: 55 }, { type: 'relation', value: 20, target: 'US', secret: true }],
    fails: [{ type: 'stability', value: 15 }] }),

  // ======================= VILLES =======================
  S({ id: 'st-megapole', cats: ['villes', 'dev'], country: 'NG', years: 15, difficulty: 'hard', icon: 'building-2', tag: 'Villes', title: 'La mégapole',
    desc: 'Des millions de nouveaux habitants arrivent chaque année. Logements, routes, emplois : suivez le rythme.',
    objectives: [{ type: 'infra', value: 25, main: true }, { type: 'pop', value: 20 }, { type: 'stability', value: 55 }, { type: 'gdp', value: 1.6, secret: true }],
    fails: [{ type: 'stability', value: 20 }] }),
  S({ id: 'st-capitale', cats: ['villes'], country: 'ID', years: 12, difficulty: 'normal', icon: 'landmark', tag: 'Villes', title: 'La nouvelle capitale',
    desc: 'La capitale s’enfonce sous la mer. Bâtissez un nouveau centre du pouvoir et reliez-le au reste du territoire.',
    objectives: [{ type: 'projects', value: 6, main: true }, { type: 'infra', value: 18 }, { type: 'debt', value: 60, optional: true }],
    events: [{ at: 1, title: 'Premier chantier', text: 'Les travaux de la nouvelle capitale commencent.', fx: { money: -0.01, infra: 3 }, tone: 'good' }] }),
  S({ id: 'st-smartcity', cats: ['villes', 'tech'], country: 'KR', years: 8, difficulty: 'discovery', icon: 'building-2', tag: 'Villes', title: 'Villes intelligentes',
    desc: 'Faites de vos villes les plus connectées du monde.',
    objectives: [{ type: 'techLevel', value: 96, main: true }, { type: 'infra', value: 8 }, { type: 'stability', value: 70, optional: true }] }),

  // ======================= MONDE ALTERNATIF =======================
  S({ id: 'st-europe-unie', cats: ['alt'], country: 'FR', years: 12, difficulty: 'normal', icon: 'sparkles', tag: 'Monde alternatif', title: 'Les États-Unis d’Europe',
    desc: 'Et si l’Europe avait choisi la fédération ? Toutes ses grandes nations sont alliées : faites-en la première puissance du monde.',
    start: { blocs: [['@', 'DE', 'IT', 'ES', 'PL', 'NL', 'BE', 'PT', 'AT', 'GR', 'SE', 'CZ']] },
    objectives: [{ type: 'rank', value: 3, main: true }, { type: 'techLevel', value: 90 }, { type: 'trade', value: 6 }, { type: 'peace', secret: true }] }),
  S({ id: 'st-empire-inca', cats: ['alt'], country: 'PE', years: 15, difficulty: 'expert', icon: 'mountain', tag: 'Monde alternatif', title: 'Le Tawantinsuyu',
    desc: 'Un grand État andin renaît et rêve d’unir les peuples de la cordillère.',
    start: { army: 40, personalities: { PE: 'expansionist' } },
    objectives: [{ type: 'gain', value: 40, main: true }, { type: 'stability', value: 50 }, { type: 'relation', value: 30, target: 'BR', optional: true }],
    fails: [{ type: 'capital' }] }),
  S({ id: 'st-japon-ferme', cats: ['alt'], country: 'JP', years: 10, difficulty: 'hard', icon: 'lock', tag: 'Monde alternatif', title: 'Le pays fermé',
    desc: 'Le Japon a refermé ses frontières au monde. Rouvrez-le avant que le pays ne s’essouffle.',
    start: { relAll: -40, gdp: -10 },
    objectives: [{ type: 'trade', value: 5, main: true }, { type: 'relation', value: 30, target: 'US' }, { type: 'gdp', value: 1.2 }, { type: 'alliances', value: 2, secret: true }] }),
  S({ id: 'st-pacte-sud', cats: ['alt', 'diplo'], country: 'BR', years: 12, difficulty: 'normal', icon: 'globe', tag: 'Monde alternatif', title: 'Le pacte du Sud',
    desc: 'L’Amérique du Sud, l’Afrique australe et l’Inde forment un bloc. Faites-en un contrepoids mondial.',
    start: { blocs: [['@', 'AR', 'ZA', 'IN', 'CL']] },
    objectives: [{ type: 'trade', value: 6, main: true }, { type: 'rank', value: 6 }, { type: 'alliances', value: 6, secret: true }] }),

  // ======================= CRISES =======================
  S({ id: 'st-pandemie', cats: ['crises'], country: 'ES', years: 6, difficulty: 'normal', icon: 'biohazard', tag: 'Crises', title: 'La pandémie',
    desc: 'Une épidémie paralyse l’économie. Protégez la population, puis relancez le pays.',
    events: [{ at: 0.2, title: 'Confinement', text: 'L’activité s’arrête presque entièrement.', fx: { gdp: -0.12, stability: -6 }, tone: 'bad' },
      { at: 2, title: 'Vaccins disponibles', text: 'La campagne de vaccination commence.', fx: { stability: 6 }, tone: 'good' }],
    objectives: [{ type: 'gdp', value: 1.05, main: true }, { type: 'stability', value: 60 }, { type: 'debt', value: 130, optional: true }],
    fails: [{ type: 'stability', value: 20 }] }),
  S({ id: 'st-secheresse', cats: ['crises', 'survie'], country: 'MA', years: 8, difficulty: 'hard', icon: 'wheat', tag: 'Crises', title: 'La grande sécheresse',
    desc: 'Les récoltes s’effondrent trois années de suite. Évitez la famine et l’exode.',
    events: [{ at: 1, title: 'Récoltes perdues', text: 'Les céréales manquent dans les campagnes.', fx: { gdp: -0.05, stability: -7 }, tone: 'bad' },
      { at: 3, title: 'Deuxième année sèche', text: 'Les réserves d’eau sont au plus bas.', fx: { gdp: -0.04, stability: -5 }, tone: 'bad' }],
    objectives: [{ type: 'stability', value: 50, main: true }, { type: 'trade', value: 3 }, { type: 'infra', value: 8, secret: true }],
    fails: [{ type: 'stability', value: 18 }] }),
  S({ id: 'st-krach', cats: ['crises', 'eco'], country: 'US', years: 8, difficulty: 'expert', icon: 'cloud-lightning', tag: 'Crises', title: 'Le krach',
    desc: 'Les marchés s’effondrent, les banques vacillent. Empêchez la crise de tourner à la dépression mondiale.',
    events: [{ at: 0.3, title: 'Lundi noir', text: 'La bourse perd un quart de sa valeur en une séance.', fx: { gdp: -0.08, stability: -6, money: -0.01 }, tone: 'bad' }],
    objectives: [{ type: 'gdp', value: 1.1, main: true }, { type: 'rank', value: 1 }, { type: 'debt', value: 150, optional: true }],
    fails: [{ type: 'stability', value: 25 }] }),
  S({ id: 'st-refugies', cats: ['crises', 'diplo'], country: 'JO', years: 8, difficulty: 'hard', icon: 'users', tag: 'Crises', title: 'Terre d’accueil',
    desc: 'Une guerre voisine pousse des centaines de milliers de réfugiés vers vos frontières.',
    start: { aiWars: [['IQ', 'SY']] },
    events: [{ at: 0.5, title: 'Afflux de réfugiés', text: 'Les camps débordent.', fx: { popGrowth: 0.6, stability: -6, money: -0.005 }, tone: 'bad' }],
    objectives: [{ type: 'stability', value: 55, main: true }, { type: 'peace' }, { type: 'trade', value: 3, optional: true }],
    fails: [{ type: 'stability', value: 20 }] }),

  // ======================= CHAOS =======================
  S({ id: 'st-chaos-monde', cats: ['chaos'], country: 'MX', years: 10, difficulty: 'grand', icon: 'flame', tag: 'Chaos', title: 'Le monde en feu',
    desc: 'Les guerres éclatent partout en même temps. Restez debout pendant que les empires s’effondrent.',
    start: { aiWars: [['RU', 'UA'], ['IN', 'PK'], ['CN', 'VN'], ['DZ', 'MA'], ['VE', 'CO'], ['ET', 'SO'], ['IR', 'IQ']] },
    objectives: [{ type: 'peace', main: true }, { type: 'gdp', value: 1.2 }, { type: 'rank', value: 10, secret: true }],
    fails: [{ type: 'stability', value: 20 }] }),
  S({ id: 'st-chaos-tous', cats: ['chaos', 'survie'], country: 'DE', years: 6, difficulty: 'grand', icon: 'skull', tag: 'Chaos', title: 'Tous contre un',
    desc: 'Vos voisins se liguent contre vous. Survivez à la coalition.',
    start: { relAll: -45, personalities: { FR: 'expansionist', PL: 'expansionist' }, hostile: ['FR', 'PL', 'NL', 'CZ', 'AT'] },
    events: [{ at: 0.4, title: 'Déclaration de guerre', text: 'La coalition passe à l’attaque.', war: 'FR', tone: 'bad' },
      { at: 0.8, title: 'Deuxième front', text: 'Un second voisin entre en guerre.', war: 'PL', tone: 'bad' }],
    objectives: [{ type: 'survive', main: true }, { type: 'territory', value: 25 }, { type: 'alliances', value: 1, secret: true }],
    fails: [{ type: 'capital' }] }),
  S({ id: 'st-chaos-revolution', cats: ['chaos', 'crises'], country: 'FR', years: 6, difficulty: 'expert', icon: 'flame', tag: 'Chaos', title: 'La révolution',
    desc: 'Le pays s’embrase. Rétablissez l’ordre sans perdre l’adhésion du peuple.',
    start: { stability: -40, gdp: -10 },
    events: [{ at: 1, title: 'Barricades', text: 'La capitale est paralysée par les manifestations.', fx: { stability: -5, gdp: -0.03 }, tone: 'bad' }],
    objectives: [{ type: 'stability', value: 60, main: true }, { type: 'gdp', value: 1.1 }, { type: 'peace', optional: true }],
    fails: [{ type: 'stability', value: 5 }] }),
  S({ id: 'st-chaos-blocs', cats: ['chaos', 'geo'], country: 'IN', years: 12, difficulty: 'grand', icon: 'swords', tag: 'Chaos', title: 'La guerre des blocs',
    desc: 'Deux alliances géantes se font face. Choisissez votre camp, ou restez le dernier grand pays libre.',
    start: { blocs: [['US', 'GB', 'FR', 'DE', 'JP', 'AU', 'CA'], ['CN', 'RU', 'IR', 'KP', 'BY']], aiWars: [['CN', 'JP']] },
    objectives: [{ type: 'rank', value: 3, main: true }, { type: 'territory', value: 0 }, { type: 'peace', secret: true }],
    fails: [{ type: 'capital' }] }),
];
